var itemLookup = {
     "immortal-kings-stature": ["Immortal King's Stature", 0, ""],
     "boots-of-disregard-29WPmn": ["Boots of Disregard", 0, ""],
     "bane-of-the-powerful": ["Bane of the Powerful", 405775, "Unique_Gem_001_x1"],
     "helltrapper-3tfdaj": ["Helltrapper", 271914, "Unique_HandXBow_102_x1"],
     "ring-of-royal-grandeur-3qRFop": ["Ring of Royal Grandeur", 298094, "ring_norm_unique_031"],
     "sanguinary-vambraces-1385JU": ["Sanguinary Vambraces", 298120, ""],
     "prides-fall-pgClp": ["Pride's Fall", 298147, ""],
     "insatiable-belt-1Yuo9W": ["Insatiable Belt", 298126, ""],
     "salvation-TxMPT": ["Salvation", 299418, ""],
     "gloves-of-worship-FA37P": ["Gloves of Worship", 332344, ""],
     "avarice-band-3qROK2": ["Avarice Band", 298095, ""],
     "mad-monarchs-scepter-2F34bH": ["Mad Monarch's Scepter", 271663, ""],
     "golden-gorget-of-leoric-1I0CCL": ["Golden Gorget of Leoric", 298052, ""],
     "illusory-boots-29WYI0": ["Illusory Boots", 332342, ""],
     "pauldrons-of-the-skeleton-king-2AGH0r": ["Pauldrons of the Skeleton King", 298164, ""],
     "split-tusk": ["Split Tusk", 221167, "voodooMask_norm_unique_03"],
     "quetzalcoatl": ["Quetzalcoatl", 204136, "voodooMask_norm_base_05"],
     "carnevil": ["Carnevil", 299442, "voodoomask_norm_unique_07"],
     "mask-of-jeram": ["Mask of Jeram", 299443, ""],
     "the-grin-reaper": ["The Grin Reaper", 221166, "voodooMask_norm_unique_01"],
     "tiklandian-visage": ["Tiklandian Visage", 221382, "voodooMask_norm_unique_06"],
     "visage-of-giyua": ["Visage of Giyua", 221168, "voodooMask_norm_unique_05"],
     "zunimassas-vision": ["Zunimassa's Vision", 221202, "voodooMask_norm_unique_04"],
     "see-no-evil": ["See No Evil", 222171, "spiritStone_norm_unique_13"],
     "gyana-na-kashu": ["Gyana Na Kashu", 222169, "spiritStone_norm_unique_05"],
     "erlang-shen": ["Erlang Shen", 222173, "spiritStone_norm_unique_07"],
     "the-minds-eye": ["The Mind's Eye", 222172, "spiritstone_norm_unique_06"],
     "eye-of-peshkov": ["Eye of Peshkov", 299464, "spiritstone_norm_unique_16"],
     "kekegis-unbreakable-spirit": ["Kekegi's Unbreakable Spirit", 299461, "spiritstone_norm_unique_15"],
     "the-laws-of-seph": ["The Laws of Seph", 299454, "spiritstone_norm_unique_14"],
     "bezoar-stone": ["Bezoar Stone", 222306, "spiritStone_norm_unique_11"],
     "the-eye-of-the-storm": ["The Eye of the Storm", 222170, "spiritStone_norm_unique_02"],
     "madstone": ["Madstone", 221572, "spiritStone_norm_unique_03"],
     "tzo-krins-gaze": ["Tzo Krin's Gaze", 222305, "spiritStone_norm_unique_12"],
     "innas-radiance": ["Inna's Radiance", 222307, "spiritStone_norm_unique_08"],
     "the-swami": ["The Swami", 218681, "wizardhat_norm_unique_03"],
     "dark-mages-shade": ["Dark Mage's Shade", 224908, "wizardhat_norm_unique_05"],
     "archmages-vicalyke": ["Archmage's Vicalyke", 299471, "wizardhat_norm_unique_06"],
     "the-magistrate": ["The Magistrate", 325579, "wizardhat_norm_unique_08"],
     "velvet-camaral": ["Velvet Camaral", 299472, "wizardhat_norm_unique_07"],
     "storm-crow": ["Storm Crow", 220694, "wizardHat_norm_unique_04"],
     "homing-pads": ["Homing Pads", 198573, "shoulderPads_norm_unique_01"],
     "borns-pauldrons": ["Born's Impunity", 0, ""],
     "death-watch-mantle": ["Death Watch Mantle", 200310, "shoulderPads_norm_unique_02"],
     "profane-pauldrons": ["Profane Pauldrons", 298158, "shoulderpads_norm_unique_08"],
     "spaulders-of-zakara": ["Spaulders of Zakara", 298163, "shoulderpads_norm_unique_09"],
     "aughilds-triumph": ["Aughild's Reign", 0, ""],
     "ashearas-vigilance": ["Asheara's Guard", 0, ""],
     "vile-ward": ["Vile Ward", 201325, "shoulderPads_norm_unique_03"],
     "seven-sins": ["Seven Sins", 0, ""],
     "demons-wings": ["Demon's Flight", 0, ""],
     "corruption": ["Corruption", 223619, "shoulderPads_norm_unique_04"],
     "ashearas-custodian": ["Asheara's Custodian", 225132, "shoulderPads_norm_unique_07"],
     "aughilds-power": ["Aughild's Power", 299443, "voodoomask_norm_unique_08"],
     "borns-privilege": ["Born's Privilege", 0, ""],
     "burden-of-the-invoker": ["Burden of the Invoker", 335029, "shoulderpads_norm_set_12"],
     "demons-aileron": ["Demon's Aileron", 224397, "shoulderPads_norm_unique_06"],
     "firebirds-pinions": ["Firebird's Pinions", 358792, "shoulderpads_norm_set_06"],
     "helltooth-mantle": ["Helltooth Mantle", 340525, "shoulderpads_norm_set_16"],
     "jade-harvesters-joy": ["Jade Harvester's Joy", 338042, "shoulderpads_norm_set_09"],
     "mantle-of-the-upsidedown-sinners": ["Mantle of the Upside-Down Sinners", 0, ""],
     "marauders-spines": ["Marauder's Spines", 336996, "shoulderpads_norm_set_07"],
     "pauldrons-of-akkhan": ["Pauldrons of Akkhan", 358801, ""],
     "raekors-burden": ["Raekor's Burden", 336989, ""],
     "rolands-mantle": ["Roland's Mantle", 404699, "p1_shoulderPads_norm_set_01"],
     "spires-of-the-earth": ["Spires of the Earth", 340526, "shoulderpads_norm_set_15"],
     "sunwukos-balance": ["Sunwuko's Balance", 336175, "shoulderpads_norm_set_11"],
     "aquila-cuirass": ["Aquila Cuirass", 197203, "chestarmor_norm_unique_047"],
     "heart-of-iron": ["Heart of Iron", 205607, "chestArmor_norm_unique_074"],
     "borns-carapace": ["Born's Heart of Steel", 0, ""],
     "chaingmail": ["Chaingmail", 197204, "chestArmor_norm_unique_048"],
     "cindercoat": ["Cindercoat", 222455, ""],
     "shi-mizus-haori": ["Shi Mizu's Haori", 332200, "chestarmor_norm_unique_01"],
     "aughilds-vestments": ["Aughild's Dominion", 0, ""],
     "goldskin": ["Goldskin", 205642, "Gloves_norm_unique_078"],
     "tyraels-might": ["Tyrael's Might", 205608, "chestArmor_norm_unique_075"],
     "blackthornes-surcoat": ["Blackthorne's Surcoat", 222456, "chestArmor_norm_unique_050"],
     "immortal-kings-eternal-reign": ["Immortal King's Eternal Reign", 205613, "chestArmor_norm_unique_086"],
     "innas-vast-expanse": ["Inna's Vast Expanse", 205614, "chestArmor_norm_unique_087"],
     "tal-rashas-relentless-pursuit": ["Tal Rasha's Relentless Pursuit", 211626, "chestArmor_norm_set_01"],
     "zunimassas-marrow": ["Zunimassa's Marrow", 205615, ""],
     "robes-of-the-rydraelm": ["Robes of the Rydraelm", 0, ""],
     "demons-cage": ["Demon's Heart", 0, ""],
     "armor-of-the-kind-regent": ["Armor of the Kind Regent", 332202, "chestarmor_norm_unique_02"],
     "mantle-of-the-rydraelm": ["Mantle of the Rydraelm", 205609, "chestArmor_norm_unique_076"],
     "aughilds-rule": ["Aughild's Rule", 364697, "CraftingReagent_Legendary_Unique_InfernalMachine_Diablo_x1"],
     "borns-frozen-soul": ["Born's Frozen Soul", 197199, "chestArmor_norm_unique_044"],
     "breastplate-of-akkhan": ["Breastplate of Akkhan", 358796, "chestarmor_norm_set_10"],
     "demons-marrow": ["Demon's Marrow", 205612, "chestArmor_norm_unique_085"],
     "firebirds-breast": ["Firebird's Breast", 358788, "chestarmor_norm_set_06"],
     "heart-of-the-crashing-wave": ["Heart of the Crashing Wave", 338032, "chestarmor_norm_set_08"],
     "helltooth-tunic": ["Helltooth Tunic", 363088, "chestarmor_norm_set_16"],
     "jade-harvesters-peace": ["Jade Harvester's Peace", 338038, "chestarmor_norm_set_09"],
     "marauders-carapace": ["Marauder's Carapace", 363803, "chestarmor_norm_set_07"],
     "raekors-heart": ["Raekor's Heart", 336984, "chestarmor_norm_set_05"],
     "rolands-bearing": ["Roland's Bearing", 404095, "chestArmor_norm_base_flippy"],
     "the-shadows-bane": ["The Shadow's Bane", 332359, "chestarmor_norm_set_14"],
     "vyrs-astonishing-aura": ["Vyr's Astonishing Aura", 332357, "chestarmor_norm_set_13"],
     "beckon-sail": ["Beckon Sail", 223150, "Cloak_norm_unique_02"],
     "blackfeather": ["Blackfeather", 332206, "cloak_norm_unique_01"],
     "cape-of-the-dark-night": ["Cape of the Dark Night", 223149, "Cloak_norm_unique_01"],
     "the-cloak-of-the-garwulf": ["The Cloak of the Garwulf", 223151, "Cloak_norm_unique_03"],
     "natalyas-embrace": ["Natalya's Embrace", 208934, "Cloak_norm_set_03"],
     "leorics-crown": ["Leoric's Crown", 196024, "Helm_norm_unique_01"],
     "broken-crown": ["Broken Crown", 220630, "Helm_norm_unique_02"],
     "cains-laurel": ["Cain's Memory", 0, ""],
     "blind-faith": ["Blind Faith", 197037, "helm_norm_unique_07"],
     "deathseers-cowl": ["Deathseer's Cowl", 298146, "helm_norm_unique_14"],
     "aughilds-brow": ["Aughild's Peak", 0, ""],
     "skull-of-resonance": ["Skull of Resonance", 220549, "Helm_norm_unique_04"],
     "guardians-watch": ["Guardian's Foresight", 0, ""],
     "andariels-visage": ["Andariel's Visage", 198014, "Helm_norm_unique_03"],
     "mempo-of-twilight": ["Mempo of Twilight", 223577, "Helm_norm_unique_12"],
     "immortal-kings-triumph": ["Immortal King's Triumph", 210265, "Helm_norm_unique_08"],
     "natalyas-sight": ["Natalya's Sight", 210851, "helm_norm_unique_09"],
     "tal-rashas-guise-of-wisdom": ["Tal Rasha's Guise of Wisdom", 211531, "Helm_norm_unique_10"],
     "the-helm-of-command": ["The Helm of Command", 0, ""],
     "sages-stones": ["Sage's Orbit", 0, ""],
     "the-helm-of-rule": ["The Helm of Rule", 222889, "Helm_norm_unique_11"],
     "aughilds-spike": ["Aughild's Spike", 0, ""],
     "cains-insight": ["Cain's Insight", 222559, "Helm_norm_set_02"],
     "crown-of-the-invoker": ["Crown of the Invoker", 335028, "helm_norm_set_12"],
     "eyes-of-the-earth": ["Eyes of the Earth", 340528, "helm_norm_set_15"],
     "firebirds-plume": ["Firebird's Plume", 358791, "helm_norm_set_06"],
     "guardians-gaze": ["Guardian's Gaze", 0, ""],
     "helltooth-mask": ["Helltooth Mask", 369016, "helm_norm_set_16"],
     "helm-of-akkhan": ["Helm of Akkhan", 358799, ""],
     "jade-harvesters-wisdom": ["Jade Harvester's Wisdom", 338040, "helm_norm_set_09"],
     "marauders-visage": ["Marauder's Visage", 336994, "helm_norm_set_07"],
     "mask-of-the-searing-sky": ["Mask of the Searing Sky", 338034, "helm_norm_set_08"],
     "raekors-will": ["Raekor's Will", 336988, "helm_norm_set_05"],
     "rolands-visage": ["Roland's Visage", 404700, "Helm_norm_base_flippy"],
     "sages-apogee": ["Sage's Apogee", 221624, "Helm_inferno_set_01"],
     "sunwukos-crown": ["Sunwuko's Crown", 336173, "helm_norm_set_11"],
     "girdle-of-giants": ["Girdle of Giants", 212232, "BarbBelt_norm_unique_04"],
     "the-undisputed-champion": ["The Undisputed Champion", 193676, "BarbBelt_norm_unique_06"],
     "kotuurs-brace": ["Kotuur's Brace", 193674, "BarbBelt_norm_unique_07"],
     "pride-of-cassius": ["Pride of Cassius", 193673, "BarbBelt_norm_unique_02"],
     "chilaniks-chain": ["Chilanik's Chain", 298133, "barbbelt_norm_unique_10"],
     "dread-iron": ["Dread Iron", 193672, "BarbBelt_norm_unique_01"],
     "lamentation": ["Lamentation", 212234, "barbbelt_norm_unique_05"],
     "immortal-kings-tribal-binding": ["Immortal King's Tribal Binding", 212235, "BarbBelt_norm_unique_09"],
     "steady-strikers": ["Steady Strikers", 193686, "bracers_norm_unique_04"],
     "gungdo-gear": ["Gungdo Gear", 193688, "Bracers_norm_unique_06"],
     "slave-bonds": ["Slave Bonds", 193685, "Bracers_norm_unique_03"],
     "ancient-parthan-defenders": ["Ancient Parthan Defenders", 298116, "bracers_norm_unique_12"],
     "custerian-wristguards": ["Custerian Wristguards", 298122, "bracers_norm_unique_17"],
     "nemesis-bracers": ["Nemesis Bracers", 205615, "chestArmor_norm_unique_088"],
     "warzechian-armguards": ["Warzechian Armguards", 298115, "bracers_norm_unique_11"],
     "aughilds-demands": ["Aughild's Ultimatum", 0, ""],
     "promise-of-glory": ["Promise of Glory", 193684, "Bracers_norm_unique_02"],
     "guardians-bands": ["Guardian's Deflector", 0, ""],
     "lacuni-prowlers": ["Lacuni Prowlers", 193687, "Bracers_norm_unique_05"],
     "strongarm-bracers": ["Strongarm Bracers", 193692, "Bracers_norm_unique_07"],
     "wondrous-deflectors": ["Wondrous Deflectors", 0, ""],
     "demons-manacles": ["Demon's Revenge", 0, ""],
     "kethryes-splint": ["Kethryes' Splint", 193683, "Bracers_norm_unique_01"],
     "reapers-wraps": ["Reaper's Wraps", 298118, ""],
     "tragoul-coils": ["Trag'Oul Coils", 298119, "bracers_norm_unique_14"],
     "aughilds-search": ["Aughild's Search", 212581, "Ring_norm_unique_010"],
     "demons-animus": ["Demon's Animus", 222741, "Bracers_norm_unique_08"],
     "guardians-aversion": ["Guardian's Aversion", 0, ""],
     "krelms-buff-bracers": ["Krelm's Buff Bracers", 336185, "bracers_norm_set_02"],
     "shackles-of-the-invoker": ["Shackles of the Invoker", 335030, "bracers_norm_set_12"],
     "pox-faulds": ["Pox Faulds", 197220, "pants_norm_unique_048"],
     "cains-raiment": ["Cain's Robes", 0, ""],
     "hammer-jammers": ["Hammer Jammers", 209059, "pants_norm_unique_077"],
     "captain-crimsons-codpiece": ["Captain Crimson's Bowsprit", 0, ""],
     "hexing-pants-of-mr-yan": ["Hexing Pants of Mr. Yan", 332204, "pants_norm_unique_01"],
     "swamp-land-waders": ["Swamp Land Waders", 0, ""],
     "ashearas-cradle": ["Asheara's Gait", 0, ""],
     "depth-diggers": ["Depth Diggers", 197216, "pants_norm_unique_044"],
     "blackthornes-jousting-mail": ["Blackthorne's Jousting Mail", 222477, "pants_norm_unique_050"],
     "innas-temperance": ["Inna's Temperance", 205646, "pants_norm_unique_087"],
     "gehennas": ["Gehennas", 222476, "pants_norm_unique_049"],
     "demons-flesh": ["Demon's Scale", 0, ""],
     "skelons-deceit": ["Skelon's Deceit", 222476, ""],
     "ashearas-pace": ["Asheara's Pace", 209054, "pants_norm_unique_073"],
     "cains-habit": ["Cain's Habit", 0, ""],
     "captain-crimsons-thrust": ["Captain Crimson's Thrust", 0, ""],
     "cuisses-of-akkhan": ["Cuisses of Akkhan", 358800, "pants_norm_set_10"],
     "demons-plate": ["Demon's Plate", 205644, "pants_norm_unique_085"],
     "firebirds-down": ["Firebird's Down", 358790, "pants_norm_set_06"],
     "helltooth-leg-guards": ["Helltooth Leg Guards", 340522, "pants_norm_set_16"],
     "jade-harvesters-courage": ["Jade Harvester's Courage", 338041, "pants_norm_set_09"],
     "marauders-encasement": ["Marauder's Encasement", 336993, ""],
     "raekors-breeches": ["Raekor's Breeches", 336986, "pants_norm_set_05"],
     "rolands-determination": ["Roland's Determination", 404097, "p1_Pants_norm_set_01"],
     "scales-of-the-dancing-serpent": ["Scales of the Dancing Serpent", 338035, "pants_norm_set_08"],
     "the-shadows-coil": ["The Shadow's Coil", 332361, "pants_norm_set_14"],
     "vyrs-fantastic-finery": ["Vyr's Fantastic Finery", 332360, "pants_norm_set_13"],
     "weight-of-the-earth": ["Weight of the Earth", 340521, "pants_norm_set_15"],
     "hellfire-ring-of-strength": ["Hellfire Ring Strength", 260327, ""],
     "hellfire-ring-of-intelligence": ["Hellfire Ring Intelligence", 260327, ""],
     "hellfire-ring-of-vitality": ["Hellfire Ring Vitality", 260327, ""],
     "hellfire-ring-of-dexterity": ["Hellfire Ring Dexterity", 260327, ""],
     "hellfire-ring": ["Hellfire Ring Ring", 260327, "Ring_norm_unique_024"],
     "manald-heal": ["Manald Heal", 212546, "Ring_norm_unique_021"],
     "nagelring": ["Nagelring", 212586, "Ring_norm_unique_018"],
     "stolen-ring": ["Stolen Ring", 197839, "Ring_norm_unique_005"],
     "leorics-signet": ["Leoric's Signet", 197835, "Ring_norm_unique_002"],
     "broken-promises": ["Broken Promises", 212589, "Ring_norm_unique_006"],
     "puzzle-ring": ["Puzzle Ring", 197837, "Ring_norm_unique_004"],
     "band-of-the-rue-chambers": ["Band of the Rue Chambers", 298093, "ring_norm_unique_030"],
     "rechels-ring-of-larceny": ["Rechel's Ring of Larceny", 298091, "ring_norm_unique_028"],
     "rogars-huge-stone": ["Rogar's Huge Stone", 298090, "ring_norm_unique_027"],
     "the-tall-mans-finger": ["The Tall Man's Finger", 298088, ""],
     "wyrdward": ["Wyrdward", 298089, "ring_norm_unique_026"],
     "bulkathoss-wedding-band": ["Bul-Kathos's Wedding Band", 212603, ""],
     "eternal-union": ["Eternal Union", 212601, "Ring_norm_unique_007"],
     "justice-lantern": ["Justice Lantern", 212590, "ring_norm_unique_008"],
     "obsidian-ring-of-the-zodiac": ["Obsidian Ring of the Zodiac", 212588, "ring_norm_unique_023"],
     "halo-of-arlyse": ["Halo of Arlyse", 0, ""],
     "band-of-hollow-whispers": ["Band of Hollow Whispers", 197834, "ring_norm_unique_001"],
     "kredes-flame": ["Krede's Flame", 197836, "Ring_norm_unique_003"],
     "oculus-ring": ["Oculus Ring", 212648, "Ring_norm_unique_017"],
     "skull-grasp": ["Skull Grasp", 212618, "Ring_norm_unique_022"],
     "stone-of-jordan": ["Stone of Jordan", 212582, ""],
     "unity": ["Unity", 212581, ""],
     "litany-of-the-undaunted": ["Litany of the Undaunted", 212651, "Ring_norm_unique_015"],
     "natalyas-reflection": ["Natalya's Reflection", 212545, "Ring_norm_unique_011"],
     "the-compass-rose": ["The Compass Rose", 212587, "Ring_norm_unique_013"],
     "the-wailing-host": ["The Wailing Host", 212650, "ring_norm_unique_014"],
     "zunimassas-pox": ["Zunimassa's Pox", 212579, "Ring_norm_unique_012"],
     "focus": ["Focus", 332209, "ring_norm_set_001"],
     "restraint": ["Restraint", 332210, "ring_norm_set_002"],
     "cains-warmers": ["Cain's Scribe", 0, ""],
     "stone-gauntlets": ["Stone Gauntlets", 205640, "Gloves_norm_unique_076"],
     "magefist": ["Magefist", 197206, "Gloves_norm_unique_044"],
     "st-archews-gage": ["St. Archew's Gage", 332172, "gloves_norm_unique_01"],
     "pendergrasps": ["Pendergrasps", 0, ""],
     "gladiator-gauntlets": ["Gladiator Gauntlets", 205635, "Gloves_norm_unique_090"],
     "ashearas-clasp": ["Asheara's Iron Fist", 0, ""],
     "frostburn": ["Frostburn", 197205, "Gloves_norm_unique_043"],
     "tasker-and-theo": ["Tasker and Theo", 205642, ""],
     "immortal-kings-irons": ["Immortal King's Irons", 205631, "Gloves_norm_unique_086"],
     "sages-grasp": ["Sage's Gesture", 0, ""],
     "penders-purchase": ["Penders Purchase", 197207, "Gloves_norm_unique_045"],
     "ashearas-ward": ["Asheara's Ward", 205636, "Gloves_norm_unique_073"],
     "cains-scriviner": ["Cain's Scrivener", 0, ""],
     "firebirds-talons": ["Firebird's Talons", 358789, "gloves_norm_set_06"],
     "fists-of-thunder": ["Fists of Thunder", 338033, "gloves_norm_set_08"],
     "gauntlets-of-akkhan": ["Gauntlets of Akkhan", 358798, ""],
     "helltooth-gauntlets": ["Helltooth Gauntlets", 363094, "gloves_norm_set_16"],
     "jade-harvesters-mercy": ["Jade Harvester's Mercy", 338039, "gloves_norm_set_09"],
     "marauders-gloves": ["Marauder's Gloves", 336992, "gloves_norm_set_07"],
     "pride-of-the-invoker": ["Pride of the Invoker", 335027, "gloves_norm_set_12"],
     "pull-of-the-earth": ["Pull of the Earth", 340523, "gloves_norm_set_15"],
     "raekors-wraps": ["Raekor's Wraps", 336985, "gloves_norm_set_05"],
     "rolands-grasp": ["Roland's Grasp", 404096, "Gloves_norm_base_flippy"],
     "sages-purchase": ["Sage's Purchase", 205632, "Gloves_norm_unique_087"],
     "sunwukos-paws": ["Sunwuko's Paws", 336172, "gloves_norm_set_11"],
     "the-shadows-grasp": ["The Shadow's Grasp", 332362, "gloves_norm_set_14"],
     "vyrs-grasping-gauntlets": ["Vyr's Grasping Gauntlets", 346210, "gloves_norm_set_13"],
     "lut-socks": ["Lut Socks", 205622, "Boots_norm_unique_077"],
     "the-crudest-boots": ["The Crudest Boots", 205620, "Boots_norm_unique_075"],
     "cains-slippers": ["Cain's Sandals", 0, ""],
     "boj-anglers": ["Boj Anglers", 197224, "Boots_norm_unique_045"],
     "captain-crimsons-deck-boots": ["Captain Crimson's Whalers", 197221, ""],
     "irontoe-mudsputters": ["Irontoe Mudsputters", 339125, "boots_norm_unique_04"],
     "fire-walkers": ["Fire Walkers", 205624, "Boots_norm_unique_085"],
     "lost-boys": ["Lost Boys", 205621, ""],
     "ashearas-lock": ["Asheara's Tracks", 0, ""],
     "ice-climbers": ["Ice Climbers", 222464, ""],
     "blackthornes-spurs": ["Blackthorne's Spurs", 222463, "Boots_norm_unique_050"],
     "immortal-kings-stride": ["Immortal King's Stride", 205625, "Boots_norm_unique_086"],
     "natalyas-bloody-footprints": ["Natalya's Bloody Footprints", 197223, "Boots_norm_unique_044"],
     "zunimassas-trail": ["Zunimassa's Trail", 205627, "Boots_norm_unique_088"],
     "sages-seekers": ["Sage's Journey", 0, ""],
     "board-walkers": ["Board Walkers", 205621, "Boots_norm_unique_076"],
     "ashearas-finders": ["Asheara's Finders", 205618, "Boots_norm_unique_073"],
     "cains-travelers": ["Cain's Travelers", 197225, ""],
     "captain-crimsons-waders": ["Captain Crimson's Waders", 197221, "Boots_norm_unique_043"],
     "eightdemon-boots": ["Eight-Demon Boots", 338031, ""],
     "firebirds-tarsi": ["Firebird's Tarsi", 358793, "boots_norm_set_06"],
     "helltooth-greaves": ["Helltooth Greaves", 340524, "boots_norm_set_16"],
     "jade-harvesters-swiftness": ["Jade Harvester's Swiftness", 338037, "boots_norm_set_09"],
     "marauders-treads": ["Marauder's Treads", 336995, "boots_norm_set_07"],
     "raekors-striders": ["Raekor's Striders", 336987, "boots_norm_set_05"],
     "rolands-stride": ["Roland's Stride", 404094, "p1_Boots_norm_set_01"],
     "sabatons-of-akkhan": ["Sabatons of Akkhan", 358795, "boots_norm_set_10"],
     "sages-passage": ["Sage's Passage", 0, ""],
     "the-shadows-heels": ["The Shadow's Heels", 332364, "boots_norm_set_14"],
     "vyrs-swaggering-stance": ["Vyr's Swaggering Stance", 332363, "boots_norm_set_13"],
     "goldwrap": ["Goldwrap", 193671, "belt_norm_unique_08"],
     "vigilante-belt": ["Vigilante Belt", 193665, "Belt_norm_unique_02"],
     "quick-draw-belt": ["Quick Draw Belt", 0, ""],
     "saffron-wrap": ["Saffron Wrap", 193664, "Belt_norm_unique_01"],
     "string-of-ears": ["String of Ears", 193669, "Belt_norm_unique_06"],
     "captain-crimsons-brace": ["Captain Crimson's Satin Sash", 0, ""],
     "cord-of-the-sherma": ["Cord of the Sherma", 298127, "belt_norm_unique_18"],
     "harrington-waistguard": ["Harrington Waistguard", 210432, "StaffOfCow"],
     "hwoj-wrap": ["Hwoj Wrap", 193670, "Belt_norm_unique_07"],
     "razor-strop": ["Razor Strop", 298124, "belt_norm_unique_15"],
     "sash-of-knives": ["Sash of Knives", 298125, "belt_norm_unique_16"],
     "sebors-nightmare": ["Sebor's Nightmare", 299381, "belt_norm_unique_22"],
     "angel-hair-braid": ["Angel Hair Braid", 193666, "belt_norm_unique_03"],
     "thundergods-vigor": ["Thundergod's Vigor", 212230, "BarbBelt_norm_unique_03"],
     "guardians-scabbard": ["Guardian's Sheath", 0, ""],
     "belt-of-the-trove": ["Belt of the Trove", 0, ""],
     "hellcat-waistguard": ["Hellcat Waistguard", 193668, ""],
     "the-witching-hour": ["The Witching Hour", 193670, ""],
     "blackthornes-notched-belt": ["Blackthorne's Notched Belt", 224191, "Belt_norm_unique_14"],
     "innas-favor": ["Inna's Favor", 222487, "Belt_norm_unique_10"],
     "tal-rashas-brace": ["Tal Rasha's Brace", 212657, "Belt_norm_unique_09"],
     "demons-binding": ["Demon's Lock", 0, ""],
     "jangs-envelopment": ["Jang's Envelopment", 298130, ""],
     "fleeting-strap": ["Fleeting Strap", 193667, "Belt_norm_unique_04"],
     "captain-crimsons-silk-girdle": ["Captain Crimson's Silk Girdle", 222974, "Belt_norm_unique_12"],
     "demons-restraint": ["Demon's Restraint", 0, ""],
     "guardians-case": ["Guardian's Case", 222976, "Belt_norm_unique_13"],
     "krelms-buff-belt": ["Krelm's Buff Belt", 0, ""],
     "hellfire-amulet-of-strength": ["Hellfire Amulet Strength", 298057, ""],
     "hellfire-amulet-of-intelligence": ["Hellfire Amulet Intelligence", 298057, ""],
     "hellfire-amulet-of-dexterity": ["Hellfire Amulet Dexterity", 298057, ""],
     "moonlight-ward": ["Moonlight Ward", 197813, "Amulet_norm_unique_03"],
     "squirts-necklace": ["Squirt's Necklace", 197819, "amulet_norm_unique_08"],
     "eye-of-etlich": ["Eye of Etlich", 197823, "Amulet_norm_unique_12"],
     "rondals-locket": ["Rondal's Locket", 197818, "Amulet_norm_unique_07"],
     "talisman-of-aranoch": ["Talisman of Aranoch", 197821, ""],
     "ancestors-grace": ["Ancestors' Grace", 0, ""],
     "countess-julias-cameo": ["Countess Julia's Cameo", 192468, "Mojo_norm_unique_02"],
     "dovu-energy-trap": ["Dovu Energy Trap", 298054, "amulet_norm_unique_23"],
     "haunt-of-vaxo": ["Haunt of Vaxo", 222464, "Boots_norm_unique_051"],
     "rakoffs-glass-of-life": ["Rakoff's Glass of Life", 298055, "amulet_norm_unique_24"],
     "the-ess-of-johan": ["The Ess of Johan", 298051, "amulet_norm_unique_20"],
     "holy-beacon": ["Holy Beacon", 197822, "amulet_norm_unique_11"],
     "kymbos-gold": ["Kymbo's Gold", 216525, "Mojo_norm_unique_07"],
     "the-flavor-of-time": ["The Flavor of Time", 193659, "Amulet_norm_unique_01"],
     "maras-kaleidoscope": ["Mara's Kaleidoscope", 197824, ""],
     "ouroboros": ["Ouroboros", 197815, "Amulet_norm_unique_05"],
     "the-star-of-azkaranth": ["The Star of Azkaranth", 197817, "amulet_norm_unique_06"],
     "xephirian-amulet": ["Xephirian Amulet", 197814, "Amulet_norm_unique_04"],
     "blackthornes-duncraig-cross": ["Blackthorne's Duncraig Cross", 298050, "amulet_norm_unique_19"],
     "tal-rashas-allegiance": ["Tal Rasha's Allegiance", 222486, "Amulet_norm_unique_14"],
     "the-travelers-pledge": ["The Traveler's Pledge", 222490, "Amulet_norm_unique_15"],
     "halcyons-ascent": ["Halcyon's Ascent", 298056, "amulet_norm_unique_25"],
     "sunwukos-shines": ["Sunwuko's Shines", 336174, "amulet_norm_set_11"],
     "gazing-demise": ["Gazing Demise", 194995, "Mojo_norm_unique_05"],
     "homunculus": ["Homunculus", 194991, "Mojo_norm_unique_04"],
     "bitterness": ["Bitterness", 194988, "Mojo_norm_unique_03"],
     "shukranis-triumph": ["Shukrani's Triumph", 272070, "mojo_norm_unique_11"],
     "thing-of-the-deep": ["Thing of the Deep", 192468, ""],
     "uhkapian-serpent": ["Uhkapian Serpent", 191278, "Mojo_norm_unique_01"],
     "manajumas-gory-fetch": ["Manajuma's Gory Fetch", 210993, "Mojo_norm_unique_06"],
     "zunimassas-string-of-skulls": ["Zunimassa's String of Skulls", 216525, ""],
     "spite": ["Spite", 0, ""],
     "winter-flurry": ["Winter Flurry", 184199, "orb_norm_unique_01"],
     "light-of-grace": ["Light of Grace", 272038, "orb_norm_unique_09"],
     "mirrorball": ["Mirrorball", 272022, "orb_norm_unique_07"],
     "mykens-ball-of-hate": ["Myken's Ball of Hate", 272037, "orb_norm_unique_08"],
     "singularity": ["Singularity", 0, ""],
     "the-oculus": ["The Oculus", 192320, "orb_norm_unique_02"],
     "triumvirate": ["Triumvirate", 195325, "orb_norm_unique_04"],
     "chantodos-force": ["Chantodo's Force", 212277, "orb_norm_unique_05"],
     "tal-rashas-unwavering-glare": ["Tal Rasha's Unwavering Glare", 212780, "orb_norm_unique_06"],
     "cosmic-strand": ["Cosmic Strand", 195127, "orb_norm_unique_03"],
     "firebirds-eye": ["Firebird's Eye", 358819, "orb_norm_set_06"],
     "denial": ["Denial", 152666, "Shield_norm_unique_03"],
     "wall-of-bone": ["Wall of Bone", 152667, "Shield_norm_unique_04"],
     "defender-of-westmarch": ["Defender of Westmarch", 298182, "shield_norm_unique_09"],
     "eberli-charo": ["Eberli Charo", 298186, "shield_norm_unique_10"],
     "freeze-of-deflection": ["Freeze of Deflection", 61550, "Shield_norm_unique_01"],
     "votoyias-spiker": ["Vo'Toyias Spiker", 298188, "shield_norm_unique_12"],
     "lidless-wall": ["Lidless Wall", 195389, "Shield_norm_unique_07"],
     "ivory-tower": ["Ivory Tower", 197478, "Shield_norm_unique_08"],
     "stormshield": ["Stormshield", 192484, "Shield_norm_unique_06"],
     "hallowed-barrier": ["Hallowed Defender", 0, ""],
     "wall-of-man": ["Wall of Man", 152667, ""],
     "hallowed-barricade": ["Hallowed Barricade", 223758, "Shield_norm_set_01"],
     "akarats-awakening": ["Akarat's Awakening", 299414, "crushield_norm_unique_04"],
     "hallowed-bulwark": ["Hallowed Bulwark", 299413, "crushield_norm_unique_03"],
     "hellskull": ["Hellskull", 299415, "crushield_norm_unique_05"],
     "jekangbord": ["Jekangbord", 299412, "crushield_norm_unique_02"],
     "sublime-conviction": ["Sublime Conviction", 299416, "crushield_norm_unique_06"],
     "the-final-witness": ["The Final Witness", 299417, "crushield_norm_unique_07"],
     "frydehrs-wrath": ["Frydehr’s Wrath", 405429, ""],
     "piro-marella": ["Piro Marella", 299411, "crushield_norm_unique_01"],
     "unrelenting-phalanx": ["Unrelenting Phalanx", 405514, ""],
     "fletchers-pride": ["Fletcher's Pride", 197629, "Quiver_norm_unique_06"],
     "sin-seekers": ["Sin Seekers", 197625, "Quiver_norm_unique_02"],
     "holy-point-shot": ["Holy Point Shot", 197627, "Quiver_norm_unique_04"],
     "spines-of-seething-hatred": ["Spines of Seething Hatred", 197628, ""],
     "bombardiers-rucksack": ["Bombardier's Rucksack", 298171, ""],
     "emimeis-duffel": ["Emimei's Duffel", 298172, "quiver_norm_unique_10"],
     "the-ninth-cirri-satchel": ["The Ninth Cirri Satchel", 298170, "quiver_norm_unique_08"],
     "meticulous-bolts": ["Meticulous Bolts", 197624, ""],
     "dead-mans-legacy": ["Dead Man's Legacy", 197630, "quiver_norm_unique_07"],
     "black-bone-arrows": ["Black Bone Arrows", 0, ""],
     "archfiend-arrows": ["Archfiend Arrows", 197626, "Quiver_norm_unique_03"],
     "genzaniku": ["Genzaniku", 116386, "Axe_norm_unique_01"],
     "flesh-tearer": ["Flesh Tearer", 358801, "shoulderpads_norm_set_10"],
     "hack": ["Hack", 271598, "axe_norm_unique_09"],
     "the-wedge": ["The Wedge", 0, ""],
     "the-butchers-sickle": ["The Butcher's Sickle", 189973, "Axe_norm_unique_06"],
     "the-burning-axe-of-sankis": ["The Burning Axe of Sankis", 181484, "Axe_norm_unique_05"],
     "hallowed-divide": ["Hallowed Storm", 223461, ""],
     "utars-roar": ["Utar's Roar", 116387, ""],
     "hallowed-breach": ["Hallowed Breach", 223461, ""],
     "the-barber": ["The Barber", 195174, "Dagger_norm_unique_03"],
     "pig-sticker": ["Pig Sticker", 221313, "dagger_norm_unique_06"],
     "kill": ["Kill", 192579, "Dagger_norm_unique_02"],
     "wizardspike": ["Wizardspike", 219329, "Dagger_norm_unique_05"],
     "bloodmagic-blade": ["Blood-Magic Blade", 0, ""],
     "bloodmagic-edge": ["Blood-Magic Edge", 195655, ""],
     "odyn-son": ["Odyn Son", 188185, "Mace_norm_unique_08"],
     "nutcracker": ["Nutcracker", 188169, "Mace_norm_unique_03"],
     "telrandens-hand": ["Telranden's Hand", 188189, "Mace_norm_unique_09"],
     "jaces-hammer-of-vigilance": ["Jace's Hammer of Vigilance", 271648, "mace_norm_unique_10"],
     "solanium": ["Solanium", 271662, "mace_norm_unique_11"],
     "nailbiter": ["Nailbiter", 188158, "Mace_norm_unique_02"],
     "neanderthal": ["Neanderthal", 102665, "Mace_norm_unique_01"],
     "echoing-fury": ["Echoing Fury", 188181, "Mace_norm_unique_07"],
     "sun-keeper": ["Sun Keeper", 188173, ""],
     "earthshatter": ["Earthshatter", 0, ""],
     "devastator": ["Devastator", 188177, "Mace_norm_unique_06"],
     "scrimshaw": ["Scrimshaw", 197095, "Spear_norm_unique_04"],
     "arreats-law": ["Arreat's Law", 191446, "Spear_norm_unique_01"],
     "the-three-hundredth-spear": ["The Three Hundredth Spear", 196638, "Spear_norm_unique_03"],
     "empyrean-messenger": ["Empyrean Messenger", 194241, "spear_norm_unique_02"],
     "akanesh-the-herald-of-righteousness": ["Akanesh, the Herald of Righteousness", 272043, "spear_norm_unique_05"],
     "deadly-rebirth": ["Deadly Rebirth", 193433, "ceremonialDagger_norm_unique_02"],
     "umbral-oath": ["Umbral Oath", 192540, "ceremonialDagger_norm_unique_01"],
     "rhenho-flayer": ["Rhen'ho Flayer", 271745, ""],
     "sacred-harvester": ["Sacred Harvester", 403748, "p1_ceremonialDagger_norm_unique_01"],
     "the-dagger-of-darts": ["The Dagger of Darts", 403767, "p1_ceremonialDagger_norm_unique_02"],
     "last-breath": ["Last Breath", 195370, "ceremonialDagger_norm_unique_03"],
     "the-spider-queens-grasp": ["The Spider Queen's Grasp", 222978, "ceremonialDagger_norm_unique_05"],
     "starmetal-kukri": ["Starmetal Kukri", 271738, "ceremonialdagger_norm_unique_10"],
     "anessazi-edge": ["Anessazi Edge", 196250, "ceremonialDagger_norm_unique_04"],
     "the-gidbinn": ["The Gidbinn", 209246, "ceremonialDagger_norm_unique_09"],
     "manajumas-carving-knife": ["Manajuma's Carving Knife", 223365, "ceremonialDagger_norm_unique_06"],
     "hallowed-sacrifice": ["Hallowed Salvation", 0, ""],
     "living-umbral-oath": ["Living Umbral Oath", 192540, ""],
     "hallowed-sufferance": ["Hallowed Sufferance", 223396, ""],
     "darklight": ["Darklight", 299428, "flail1h_norm_unique_06"],
     "gyrfalcons-foote": ["Gyrfalcon's Foote", 299427, "flail1h_norm_unique_05"],
     "inviolable-faith": ["Inviolable Faith", 299429, "flail1h_norm_unique_07"],
     "justinians-mercy": ["Justinian's Mercy", 299424, "flail1h_norm_unique_02"],
     "kassars-retribution": ["Kassar's Retribution", 299426, "flail1h_norm_unique_04"],
     "swiftmount": ["Swiftmount", 299425, "flail1h_norm_unique_03"],
     "golden-scourge": ["Golden Scourge", 299419, ""],
     "monster-hunter": ["Monster Hunter", 115140, "Sword_norm_unique_01"],
     "wildwood": ["Wildwood", 270978, ""],
     "borns-seething-rage": ["Born's Searing Spite", 0, ""],
     "doombringer": ["Doombringer", 185397, "sword_norm_unique_07"],
     "the-ancient-bonesaber-of-zumakalis": ["The Ancient Bonesaber of Zumakalis", 194481, "Sword_norm_unique_08"],
     "exarian": ["Exarian", 271617, "sword_norm_unique_13"],
     "fulminator": ["Fulminator", 271631, "sword_norm_unique_15"],
     "gift-of-silaria": ["Gift of Silaria", 271630, "sword_norm_unique_14"],
     "rimeheart": ["Rimeheart", 271636, "sword_norm_unique_20"],
     "thunderfury-blessed-blade-of-the-windseeker": ["Thunderfury, Blessed Blade of the Windseeker", 229716, "sword_norm_unique_12"],
     "sever": ["Sever", 115141, "Sword_norm_unique_02"],
     "skycutter": ["Skycutter", 182347, "Sword_norm_unique_04"],
     "azurewrath": ["Azurewrath", 192511, "sword_norm_unique_06"],
     "devil-tongue": ["Devil Tongue", 189552, "Sword_norm_unique_05"],
     "griswolds-masterpiece": ["Griswold's Masterpiece", 0, ""],
     "griswolds-perfection": ["Griswold's Perfection", 270977, "Sword_norm_unique_10"],
     "shard-of-hate": ["Shard of Hate", 376463, "sword_norm_promo_02"],
     "borns-furious-wrath": ["Born's Furious Wrath", 223408, "Sword_norm_set_01"],
     "little-rogue": ["Little Rogue", 313291, "sword_norm_set_03"],
     "the-slanderer": ["The Slanderer", 313290, "sword_norm_set_02"],
     "the-executioner": ["The Executioner", 186560, "twoHandedAxe_norm_unique_02"],
     "butchers-carver": ["Butcher's Carver", 186494, "twoHandedAxe_norm_unique_03"],
     "messerschmidts-reaver": ["Messerschmidt's Reaver", 191065, "twoHandedAxe_norm_unique_04"],
     "skorn": ["Skorn", 192887, "twoHandedAxe_norm_unique_05"],
     "fire-brand": ["Fire Brand", 0, ""],
     "cinder-switch": ["Cinder Switch", 6329, "twoHandedAxe_norm_unique_01"],
     "fjord-cutter": ["Fjord Cutter", 192105, "mightyWeapon_1H_norm_unique_01"],
     "ambos-pride": ["Ambo's Pride", 193486, "mightyweapon_1h_norm_unique_03"],
     "harvest-moon": ["Harvest Moon", 0, ""],
     "blade-of-the-warlord": ["Blade of the Warlord", 193611, "mightyweapon_1h_norm_unique_04"],
     "bulkathoss-solemn-vow": ["Bul-Kathos's Solemn Vow", 208771, ""],
     "bulkathoss-warrior-blood": ["Bul-Kathos's Warrior Blood", 208775, ""],
     "hallowed-destroyer": ["Hallowed Reckoning", 0, ""],
     "nights-reaping": ["Night's Reaping", 192705, ""],
     "remorseless": ["Remorseless", 0, ""],
     "hallowed-nemesis": ["Hallowed Nemesis", 223627, ""],
     "fleshrake": ["Fleshrake", 145850, "fistWeapon_norm_unique_03"],
     "rabid-strike": ["Rabid Strike", 196472, "fistweapon_norm_unique_10"],
     "scarbringer": ["Scarbringer", 130557, "fistWeapon_norm_unique_01"],
     "sledge-fist": ["Sledge Fist", 175938, "fistWeapon_norm_unique_07"],
     "jawbreaker": ["Jawbreaker", 271957, "fistweapon_norm_unique_14"],
     "logans-claw": ["Logan's Claw", 145849, "fistweapon_norm_unique_02"],
     "demon-hand": ["Demon Hand", 0, ""],
     "crystal-fist": ["Crystal Fist", 175939, "fistWeapon_norm_unique_08"],
     "the-fist-of-azturrasq": ["The Fist of Az'Turrasq", 175937, "fistWeapon_norm_unique_06"],
     "won-khim-lau": ["Won Khim Lau", 145851, "fistWeapon_norm_unique_04"],
     "shenlongs-fist-of-legend": ["Shenlong's Fist of Legend", 208996, "fistWeapon_norm_unique_12"],
     "shenlongs-relentless-assault": ["Shenlong's Relentless Assault", 208898, "fistWeapon_norm_unique_11"],
     "hallowed-touch": ["Hallowed Hand", 223526, ""],
     "demon-claw": ["Demon Claw", 193459, ""],
     "vengeful-wind": ["Vengeful Wind", 403775, "p1_fistWeapon_norm_unique_02"],
     "hallowed-hold": ["Hallowed Hold", 223526, ""],
     "arthefs-spark-of-life": ["Arthef's Spark of Life", 59633, "twoHandedMace_norm_unique_01"],
     "crushbane": ["Crushbane", 99227, "twoHandedMace_norm_unique_02"],
     "skywarden": ["Skywarden", 190840, "twohandedmace_norm_unique_03"],
     "wrath-of-the-bone-king": ["Wrath of the Bone King", 191584, "twoHandedMace_norm_unique_06"],
     "the-furnace": ["The Furnace", 271666, "twohandedmace_norm_unique_08"],
     "cataclysm": ["Cataclysm", 0, ""],
     "schaefers-hammer": ["Schaefer's Hammer", 197717, "twoHandedMace_norm_unique_07"],
     "sledge-of-athskeleng": ["Sledge of Athskeleng", 190866, "twoHandedMace_norm_unique_04"],
     "sunder": ["Sunder", 190868, ""],
     "pledge-of-caldeum": ["Pledge of Caldeum", 196570, "Polearm_norm_unique_04"],
     "standoff": ["Standoff", 191570, "Polearm_norm_unique_01"],
     "bovine-bardiche": ["Bovine Bardiche", 272056, "polearm_norm_unique_05"],
     "heart-slaughter": ["Heart Slaughter", 192569, "polearm_norm_unique_02"],
     "vigilance": ["Vigilance", 195491, "Polearm_norm_unique_03"],
     "hellish-staff-of-herding": ["Hellish Staff of Herding", 0, ""],
     "infernal-staff-of-herding": ["Infernal Staff of Herding", 367201, "wizardhat_norm_base_02"],
     "nightmarish-staff-of-herding": ["Nightmarish Staff of Herding", 0, ""],
     "autumns-call": ["Autumn's Call", 184228, "staff_norm_unique_03"],
     "the-broken-staff": ["The Broken Staff", 59601, "staff_norm_unique_01"],
     "ahavarion-spear-of-lycander": ["Ahavarion, Spear of Lycander", 271768, "staff_norm_unique_08"],
     "the-smoldering-core": ["The Smoldering Core", 271774, "staff_norm_unique_10"],
     "valtheks-rebuke": ["Valthek's Rebuke", 271773, "staff_norm_unique_09"],
     "the-magi": ["The Magi", 0, ""],
     "maloths-focus": ["Maloth's Focus", 193832, "Staff_norm_unique_06"],
     "wormwood": ["Wormwood", 195407, "Staff_norm_unique_07"],
     "the-grand-vizier": ["The Grand Vizier", 192167, "Staff_norm_unique_04"],
     "the-tormentor": ["The Tormentor", 193066, "staff_norm_unique_05"],
     "mark-of-the-magi": ["Mark of The Magi", 59612, ""],
     "baleful-remnant": ["Baleful Remnant", 299435, "flail2h_norm_unique_02"],
     "fate-of-the-fell": ["Fate of the Fell", 299436, "flail2h_norm_unique_03"],
     "golden-flense": ["Golden Flense", 299437, "flail2h_norm_unique_04"],
     "the-mortal-drama": ["The Mortal Drama", 299431, "flail2h_norm_unique_01"],
     "faithful-memory": ["Faithful Memory", 198960, "twoHandedSword_norm_unique_09"],
     "the-zweihander": ["The Zweihander", 59665, "twohandedsword_norm_unique_01"],
     "blackguard": ["Blackguard", 270979, "twoHandedSword_norm_unique_10"],
     "scourge": ["Scourge", 181511, "twoHandedSword_norm_unique_06"],
     "stalgards-decimator": ["Stalgard's Decimator", 271639, "twohandedsword_norm_unique_11"],
     "blade-of-prophecy": ["Blade of Prophecy", 184184, "twoHandedSword_norm_unique_03"],
     "the-sultan-of-blinding-sand": ["The Sultan of Blinding Sand", 184190, "twoHandedSword_norm_unique_05"],
     "maximus": ["Maximus", 184187, "twoHandedSword_norm_unique_04"],
     "the-grandfather": ["The Grandfather", 190360, "twohandedsword_norm_unique_08"],
     "warmonger": ["Warmonger", 181495, "twoHandedSword_norm_unique_07"],
     "cams-rebuttal": ["Cam's Rebuttal", 271644, "twohandedsword_norm_unique_12"],
     "unending-war": ["Unending War", 0, ""],
     "bastions-revered": ["Bastion's Revered", 195690, "mightyWeapon_2H_norm_unique_03"],
     "fury-of-the-vanished-peak": ["Fury of the Vanished Peak", 195138, ""],
     "madawcs-sorrow": ["Madawc's Sorrow", 272012, "mightyweapon_2h_norm_unique_11"],
     "the-gavel-of-judgment": ["The Gavel of Judgment", 193657, "mightyWeapon_2H_norm_unique_01"],
     "immortal-kings-boulder-breaker": ["Immortal King's Boulder Breaker", 210678, "mightyWeapon_2H_norm_unique_10"],
     "war-of-the-dead": ["War of the Dead", 196308, ""],
     "uskang": ["Uskang", 175580, "bow_norm_unique_01"],
     "longshot": ["Longshot", 0, ""],
     "etrayu": ["Etrayu", 175581, "Bow_norm_unique_02"],
     "the-ravens-wing": ["The Raven's Wing", 221938, "Bow_norm_unique_07"],
     "kridershot": ["Kridershot", 271875, "bow_norm_unique_09"],
     "cluckeye": ["Cluckeye", 175582, "Bow_norm_unique_03"],
     "windforce": ["Windforce", 192602, "bow_norm_unique_04"],
     "venomhusk": ["Venomhusk", 0, ""],
     "leonine-bow-of-hashir": ["Leonine Bow of Hashir", 271882, "bow_norm_unique_11"],
     "odysseys-end": ["Odyssey's End", 0, ""],
     "sydyru-crust": ["Sydyru Crust", 221893, "Bow_norm_unique_06"],
     "unbound-bolt": ["Unbound Bolt", 220654, "Bow_norm_unique_05"],
     "starfire": ["Starfire", 182074, "Wand_norm_unique_04"],
     "blackhand-key": ["Blackhand Key", 193355, "wand_norm_unique_06"],
     "serpents-sparker": ["Serpent's Sparker", 272084, "wand_norm_unique_02"],
     "wand-of-woh": ["Wand of Woh", 272086, "wand_norm_unique_06"],
     "fragment-of-destiny": ["Fragment of Destiny", 181995, "Wand_norm_unique_02"],
     "gesture-of-orpheus": ["Gesture of Orpheus", 182071, "Wand_norm_unique_03"],
     "sloraks-madness": ["Slorak's Madness", 181982, "Wand_norm_unique_01"],
     "chantodos-will": ["Chantodo's Will", 210479, "Wand_norm_unique_07"],
     "ruinstoke": ["Ruinstoke", 0, ""],
     "hallowed-rod": ["Hallowed Scepter", 0, ""],
     "aether-walker": ["Aether Walker", 0, ""],
     "atrophy": ["Atrophy", 182081, "Wand_norm_unique_05"],
     "hallowed-baton": ["Hallowed Baton", 224184, ""],
     "izzuccob": ["Izzuccob", 192467, "handXbow_norm_unique_01"],
     "balefire-caster": ["Balefire Caster", 192528, "handxbow_norm_unique_02"],
     "kmar-tenclip": ["K'mar Tenclip", 271892, "handxbow_norm_unique_10"],
     "deadeye": ["Deadeye", 0, ""],
     "dawn": ["Dawn", 196409, "handXbow_norm_unique_04"],
     "calamity": ["Calamity", 225181, "handXbow_norm_unique_08"],
     "danettas-revenge": ["Danetta's Revenge", 211749, "handXbow_norm_unique_07"],
     "danettas-spite": ["Danetta's Spite", 211745, "handXbow_norm_unique_06"],
     "natalyas-slayer": ["Natalya's Slayer", 210874, "handXbow_norm_unique_05"],
     "hallowed-avenger": ["Hallowed Judgment", 0, ""],
     "blitzbolter": ["Blitzbolter", 195078, "handXbow_norm_unique_03"],
     "hallowed-condemnation": ["Hallowed Condemnation", 223763, ""],
     "demon-machine": ["Demon Machine", 222286, "xbow_norm_unique_07"],
     "burizado-kyanon": ["Buriza-Do Kyanon", 194219, ""],
     "bakkan-caster": ["Bakkan Caster", 98163, "xbow_norm_unique_01"],
     "pus-spitter": ["Pus Spitter", 204874, "XBow_norm_unique_05"],
     "starspine": ["Starspine", 0, ""],
     "hellrack": ["Hellrack", 192836, "XBow_norm_unique_02"],
     "manticore": ["Manticore", 221760, "XBow_norm_unique_06"],
     "arcane-barb": ["Arcane Barb", 194957, "XBow_norm_unique_04"],
     "chanon-bolter": ["Chanon Bolter", 271884, "xbow_norm_unique_08"],
     "wojahnni-assaulter": ["Wojahnni Assaulter", 271889, "xbow_norm_unique_09"],
     "balance": ["Balance", 195145, "combatstaff_norm_unique_04"],
     "lai-yuis-taiji": ["Lai Yui's Taiji", 0, ""],
     "the-flow-of-eternity": ["The Flow of Eternity", 197072, "combatStaff_norm_unique_06"],
     "the-paddle": ["The Paddle", 197068, "combatStaff_norm_unique_03"],
     "staff-of-kyro": ["Staff of Kyro", 271749, "combatstaff_norm_unique_09"],
     "warstaff-of-general-quang": ["Warstaff of General Quang", 271765, "combatstaff_norm_unique_10"],
     "incense-torch-of-the-grand-temple": ["Incense Torch of the Grand Temple", 192342, "combatStaff_norm_unique_01"],
     "flying-dragon": ["Flying Dragon", 197065, "combatStaff_norm_unique_02"],
     "innas-reach": ["Inna's Reach", 212208, "combatStaff_norm_unique_08"],
     "rozpedins-staff": ["Rozpedin's Staff", 0, ""],
     "lai-yuis-persuader": ["Lai Yui's Persuader", 209214, ""],
     "rozpedins-force": ["Rozpedin's Force", 196880, ""],
}
